//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal_Details
    {
        public int ProposalId { get; set; }
        public Nullable<long> SaleId { get; set; }
        public Nullable<decimal> BidPrice { get; set; }
        public Nullable<long> BidUnit { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusComments { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Proposal_Status Proposal_Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
