//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QID_Details
    {
        public int DetailsId { get; set; }
        public byte[] QID { get; set; }
        public string ShareDescription { get; set; }
        public int ShareAvailable { get; set; }
    }
}
