//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share_Details
    {
        public int ShareDetailsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string QID { get; set; }
        public Nullable<long> ShareholderID { get; set; }
        public Nullable<long> AvailableShares { get; set; }
        public string Description { get; set; }
        public string UniqueID { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
